- name: Deploy Scientific Calculator Using Docker
  hosts: local
  become: yes
  tasks:
    - name: Pull Docker Image from Docker Hub
      command: docker pull kesarwani05/scientific-calculator:latest

    - name: Stop Running Container (If Exists)
      command: docker rm -f scientific-calculator
      ignore_errors: yes

    - name: Run Docker Container
      command: docker run -d --name scientific-calculator -p 9091:8080 kesarwani05/scientific-calculator